### ISSUE TITLE
Getting: cannot load such file -- active_support/all (LoadError)

### ISSUE THREAD

**Issue by bsschang** [dracula/snippetslab#3]
Hello:

I cloned the git repository and then ran './generate.command'. I am getting the following error:

```
/usr/local/Homebrew/Library/Taps/dracula/homebrew-install/cmd/dracula-yaml-json.rb:1:in `require': cannot load such file -- active_support/all (LoadError)
	from /usr/local/Homebrew/Library/Taps/dracula/homebrew-install/cmd/dracula-yaml-json.rb:1:in `<top (required)>'
	from ./generate.rb:3:in `require'
	from ./generate.rb:3:in `<main>'
```

I have spent considerable time googling for help, but nothing I have tried is working. It's possible that I have something configured incorrectly on my side, but I'm not sure where to look.

Thank you!

**Comment by danielbayley** [comment]
@bsschang It was a problem with `brew` not having access to the necessary bundled RubyGems, since they aren’t installed by default. I pushed a fix, so please test and report back… Thanks.

Also, be sure the tap is updated:
~~~ sh
brew update
brew untap dracula/install --force
brew tap dracula/install
brew install --cask dracula-snippetslab
~~~

**Comment by bsschang** [comment]
@danielbayley It worked -- thank you!

If you are willing to share what you fixed, I'd love to learn.

Is it proper etiquette for me to close this issue since you fixed it?

**Comment by danielbayley** [comment]
> If you are willing to share what you fixed, I'd love to learn.

@bsschang Sure, it needed to ensure the [bundled RubyGems](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/Gemfile#L40-L53) were installed to be able to access and use methods from [_Active Support_](https://guides.rubyonrails.org/active_support_core_extensions.html)… See https://github.com/dracula/homebrew-install/blob/main/cmd/dracula-yaml-json.rb#L3-L4, along with a few other small fixes… Basically, the `generate.command`/`generate.rb` relies on the above [command](https://docs.brew.sh/External-Commands) (as with [other themes](https://github.com/dracula/dracula-colorslurp/blob/main/generate.command#L6)) to generate the actual `Dracula.json` theme… the failure of which was breaking the install.

> Is it proper etiquette for me to close this issue since you fixed it?

Probably… but I already did 😉

**Comment by bsschang** [comment]
@danielbayley Thank you for taking the time to explain (with links!) and help me understand.
